#!/usr/bin/env bash
# A script
if [ $# -ne 4 ]; then
    echo 'Usage: 0-transfer_file 1-PATH_TO_FILE 2-IP 3-USERNAME 4-PATH_TO_SSH_KEY'
else
    scp  -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
