#!/usr/bin/env bash
# Install nginx an create a default page
apt-get update -y
apt-get install nginx -y
echo Holberton School > /var/www/html/index.nginx-debian.html
my_string="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE=/etc/nginx/sites-available/default
result=$(grep "$my_string" "$FILE")
if [ -z "$result" ]; then
    sed -i "48 a $my_string" "$FILE"
fi
service nginx start
