#!/usr/bin/env bash
# 0. Double the number of webservers
apt-get update -y
apt-get install nginx -y
my_string="add_header X-Served-By \$HOSTNAME;"
FILE=/etc/nginx/sites-available/default
result=$(grep "$my_string" "$FILE")
if [ -z "$result" ]; then
    sed -i "48 a $my_string" "$FILE"
fi
service nginx start
service nginx reload
