#!/usr/bin/env bash
# 1. Install your load balancer
apt-get update -y
apt-get install haproxy -y

FILE=/etc/haproxy/haproxy.cfg
my_string="\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n\nbackend backendnodes\n\tbalance roundrobin\n\tserver  ws01   104.196.30.252:80 check\n\tserver  ws02   35.185.6.249:80 check"
result=$(grep "$my_string" "$FILE")
if [ -z "$result" ]; then
    echo -e "$my_string" >>"$FILE"
fi
my_string="ENABLED=1"
FILE=/etc/default/haproxy
result=$(grep "$my_string" "$FILE")
if [ -z "$result" ]; then
    echo "$my_string" >>"$FILE"
fi
service haproxy start
