#!/usr/bin/env bash
# Why you no love me?
echo $$ >/var/run/holbertonscript.pid
while :; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo Y U no love me?!' SIGINT
	trap 'rm -rf /var/run/holbertonscript.pid && echo I hate the kill command && exit' SIGTERM SIGQUIT
done
