#!/usr/bin/env bash
# script that displays numbers from 1 to 100
for x in {1..100}
do
	if ((x % 5 == 0)) && ((x % 3 == 0))
	then
		echo "FizzBuzz"
	elif ((x % 3 == 0))
	then
		echo "Fizz"
	elif ((x % 5 == 0))
	then
		echo "Buzz"
	else
		echo $x
	fi
done
