#!/usr/bin/env bash
#Print 10 times Holberton School with while
x=1
while [ $x -le 10 ]
do
        if [ $x == 4 ]
        then
                echo "bad luck"
	elif [ $x == 8 ]
	then
                echo "good luck"
	else
		echo "HolbertonSchool"
	fi
	((x=x+1))
done
