#!/usr/bin/env bash
# 1. Run Nginx as Nginx
pkill apache
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
chmod --reference=/etc/nginx/proxy_params /etc/nginx/nginx.conf
sudo -u nginx service nginx start
